### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by onix010** [deteto747chudo/TikTokViewsBot#1]
* Serving Flask app 'keep_alive' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.1.143:8080/ (Press CTRL+C to quit)

[37m[[34m-[37m] Waiting for Zefoy to load... 502 Error = Blocked country or VPN is on
 [37m[[34m-[37m] Site loaded, enter the CAPTCHA to continue.
 [37m[[34m-[37m] Solving CAPTCHA...
Message: element not interactable
  (Session info: chrome=129.0.6668.101)
Stacktrace:
	GetHandleVerifier [0x00007FF775FEB095+29557]
	(No symbol) [0x00007FF775F5FA50]
	(No symbol) [0x00007FF775E1B399]
	(No symbol) [0x00007FF775E68FB3]
	(No symbol) [0x00007FF775E6717C]
	(No symbol) [0x00007FF775E9718A]
	(No symbol) [0x00007FF775E62E86]
	(No symbol) [0x00007FF775E973A0]
	(No symbol) [0x00007FF775EB851C]
	(No symbol) [0x00007FF775E96F33]
	(No symbol) [0x00007FF775E6116F]
	(No symbol) [0x00007FF775E622D1]
	GetHandleVerifier [0x00007FF77631C96D+3378253]
	GetHandleVerifier [0x00007FF776368497+3688311]
	GetHandleVerifier [0x00007FF77635D1CB+3642539]
	GetHandleVerifier [0x00007FF7760AA6B6+813462]
	(No symbol) [0x00007FF775F6AB5F]
	(No symbol) [0x00007FF775F66B74]
	(No symbol) [0x00007FF775F66D10]
	(No symbol) [0x00007FF775F55C1F]
	BaseThreadInitThunk [0x00007FFB5FD3257D+29]
	RtlUserThreadStart [0x00007FFB6052AF08+40]

**Comment by deteto747chudo** [comment]
Hello! Thanks for reaching us out! The error might be coming from not fast CPU processing, so to fix you might need to change the delay time and add a bit more seconds so the program can load the element!
